services:
  # Frontend Service
  - type: web
    name: dashboard-frontend
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    dockerCommand: nginx -g 'daemon off;'
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    autoDeploy: true

  # Backend Service
  - type: web
    name: dashboard-backend
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    autoDeploy: true
