services:
  # Frontend Service
  - type: web
    name: dashboard-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    numInstances: 1

  # Backend Service
  - type: web
    name: dashboard-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
    healthCheckPath: /health
    numInstances: 1
