name: Docker Build and Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t dashboard-backend -f Dockerfile .
          docker build -t dashboard-frontend -f Dockerfile.frontend .

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Deploy backend service
          curl -X POST https://api.render.com/v1/services \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "type": "web",
              "name": "dashboard-backend",
              "env": "docker",
              "dockerfilePath": "./Dockerfile",
              "branch": "main"
            }'

          # Deploy frontend service
          curl -X POST https://api.render.com/v1/services \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "type": "web",
              "name": "dashboard-frontend",
              "env": "docker",
              "dockerfilePath": "./Dockerfile.frontend",
              "branch": "main"
            }'
